name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up Golang
      uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: Build Release
      run: make release
    - name: Publish
      run: .github/workflows/release.sh
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        GCLOUD_CLIENT_SECRET: ${{ secrets.GCLOUD_CLIENT_SECRET }}
