name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.3
    - name: Set up Golang
      uses: actions/setup-go@v2.1.3
      with:
        go-version: '1.14'
    - name: Build Release
      run: make release
    - name: Publish
      run: .github/workflows/release.sh
      if: |
        github.event_name == 'push' && (
          github.ref == 'refs/heads/main' || (
            startsWith(github.ref, 'refs/heads/v') && endsWith(github.ref, 'x')
          )
        )
      env:
        GCLOUD_CLIENT_SECRET: ${{ secrets.GCLOUD_CLIENT_SECRET }}
